### ISSUE TITLE
MapsGL/WebGL support for Google Maps Javascript API v3?

### ISSUE THREAD

**Issue by solidspark** [brendankenny/libtess.js#1]
Brendan,

I saw your Tessellation demo on G+ and was wondering about access to the WebGL extension of the Google Maps JS API - when will it be available? We're building out a product that uses the new visual refresh for Google Maps and the performance between the MapsGL enabled version on maps.google.com and our non-MapsGL version is night and day.

**Comment by brendankenny** [comment]
Hey Ryan,

I'm personally very excited about the new MapsGL and I'm really looking forward to it being available in the API and the things we would then be able to do with it, but there are no immediate plans for this to happen. The new maps are still invite-only, in fact. We don't really comment on product roadmaps, for better or worse, so right now the only real news relating to the new maps and the Maps API is in this blogpost:

http://googlegeodevelopers.blogspot.com/2013/05/a-fresh-new-look-for-maps-api-for-all.html

Wish I had better (and more concrete) news for you :) As I said, I'm definitely looking forward to our WebGL-rendered geo future.
